### ISSUE TITLE
Add handles redesign in SASS

### ISSUE THREAD

**Issue by ismakutl** [oSoc17/datascouts#106]
Right now we have an add button but we don't have an input. We won't use the third sidebar to add it.
You can see the design in [this link](https://drive.google.com/open?id=0B68rv2OTAiu7TGFnandSUEk2anc)

- [x] HTML
- [x] SASS

**Comment by mietcls** [comment]
@ismakutl is this done? Cloooose it

**Comment by xavez** [comment]
@ismakutl is this done? Close the issue please.

**Comment by ismakutl** [comment]
This is done, closing the issue.
