### ISSUE TITLE
Make sure data is not fetched on random times

### ISSUE THREAD

**Issue by mietcls** [oSoc17/datascouts#109]
Right now, the data is not fetched when you want it to be fetched, it does it randomly.

If this is not the source of the problem for the hard refresh and not the instant show — please create a different issue describing you're going to look for the bug.

**Comment by xavez** [comment]
@mrvdries is it clear to you how to fix this?

**Comment by Dakad** [comment]
Use the lodash debounce function when fetching data from API.
