### ISSUE TITLE
Change onboarding copy

### ISSUE THREAD

**Issue by xavez** [oSoc17/datascouts#119]
This copy:

![](http://c.xvr.io/0E1U3L0P0r3Q/Image%202017-07-25%20at%207.58.58%20PM.png)

Should change to:

# Visualise what your colleagues, friends, companies and competitors are talking about.

1. Add the name of your first company or person you want to follow. We call this a member.
2. Click on the member and add all social media channels for this member.
3. All done!

![](http://c.xvr.io/2Y3x1w42180p/Image%202017-07-25%20at%208.06.17%20PM.png)

**Comment by mietcls** [comment]
@ismakutl content is done, but please still fix the styling — make sure it can be displayed in OL instead of UL
