### ISSUE TITLE
Add a letter-spacing of 1px or 2px for all capitalised elements

### ISSUE THREAD

**Issue by mietcls** [oSoc17/datascouts#120]
Capitalisation requires some more letter-spacing to be more legible. Depending on how big it is, you have to decide if it is 1px or 2px (what looks best)

<img width="257" alt="screen shot 2017-07-25 at 21 19 48" src="https://user-images.githubusercontent.com/1572885/28589609-22716eec-717f-11e7-8508-df4813f80565.png">

<img width="150" alt="screen shot 2017-07-25 at 21 20 55" src="https://user-images.githubusercontent.com/1572885/28589625-2f939c8a-717f-11e7-9fd5-69e18843a764.png">

<img width="151" alt="screen shot 2017-07-25 at 21 20 58" src="https://user-images.githubusercontent.com/1572885/28589626-3193bf42-717f-11e7-8315-33c3aa411755.png">

<img width="328" alt="screen shot 2017-07-25 at 21 28 59" src="https://user-images.githubusercontent.com/1572885/28589888-4aff1656-7180-11e7-90b5-92b97e6c60af.png">

**Comment by ismakutl** [comment]
Done.
