### ISSUE TITLE
Style input fields consistently in popup

### ISSUE THREAD

**Issue by mietcls** [oSoc17/datascouts#122]
Right now, most of the input fields are 40px high. The one in the popup is not. Make them equal.

Right (40px)
<img width="231" alt="screen shot 2017-07-25 at 21 21 52" src="https://user-images.githubusercontent.com/1572885/28589783-cc53e0f2-717f-11e7-9cd0-554607f4ba9d.png">

Wrong (30px or anything else)
<img width="335" alt="screen shot 2017-07-25 at 21 22 03" src="https://user-images.githubusercontent.com/1572885/28589788-d27fbd98-717f-11e7-8f0a-1d2896d704d6.png">

**Comment by ismakutl** [comment]
Done.
