### ISSUE TITLE
Make font-size of input fields bigger

### ISSUE THREAD

**Issue by mietcls** [oSoc17/datascouts#123]
Input fields are now 11px. This is way too small. Use 1rem.

<img width="335" alt="screen shot 2017-07-25 at 21 22 03" src="https://user-images.githubusercontent.com/1572885/28589854-21512074-7180-11e7-8ec7-ccc760becbf3.png">
<img width="231" alt="screen shot 2017-07-25 at 21 21 52" src="https://user-images.githubusercontent.com/1572885/28589855-21531b7c-7180-11e7-99b2-ca591c9039bf.png">

**Comment by ismakutl** [comment]
Done.
