### ISSUE TITLE
Let popup breathe

### ISSUE THREAD

**Issue by mietcls** [oSoc17/datascouts#124]
- [x] If you're using Sofia Pro (anywhere, for that matter), use it uppercase. 2px letter-spacing
- [x] use dividers such as lines or white space to help the user read (for example, line underneath title)
- [x] align everything to the left so it won't look messy ( #124 )
- [x] Make sure your labels are close to the form element but not too close to the previous form element
- [x] Make your input fields big enough and make them legible ( #123, #122 )

A quick example of what this looks like when you implement these rules:

<img width="388" alt="screen shot 2017-07-25 at 21 38 41" src="https://user-images.githubusercontent.com/1572885/28590388-3125d5ce-7182-11e7-8539-97b479223197.png">

**Comment by ismakutl** [comment]
Done.
