### ISSUE TITLE
Create components for html different feeds (twitter, youtube, vimeo)

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#128]
The html for the feed of the tweets, videos etc should be made (except tweets, thats already done) and then organised in different components

- [x] Move twitter html to separate component
- [x] Youtube html
- [x] Youtube component
- [x] Vimeo html
   - [x] Style Vimeo
- [x] Vimeo component
- [x] Bonus: filter on social media
- [x] Dates

**Comment by mrvdries** [comment]
I moved all html to separate components. I couldn't test this however, since no data can be fetched.

I added a little bonus to this branch: it should be possible to now filter on social media as well. This also couldn't be tested yet.

**Comment by ismakutl** [comment]
Done.
