### ISSUE TITLE
Implement filter on key-words

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#129]
It should be possible to filter on key-word on the front-end. Html and css for this has already been partially implemented, but no actual functionality.

Additionally it should be possible to toggle, save and delete these key-words in a list.

Maybe filter on multiple key-words at once

- [x] filter on key-word functionality
- [x] a button to delete a keyword
- [x] key-word list
- [x] css styling
  - [x] (multiple key-words?)
### Extra:
- [x] Minify css (command: 'gulp minify-css')

**Comment by mrvdries** [comment]
Styling for the keyword list should be done too @ismakutl

**Comment by mrvdries** [comment]
Now possible to add, select and delete keywords. Choose "no filter" to turn off keyword filtering. Needs to be styled and tested with fetch data (currently not possible).

**Comment by ismakutl** [comment]
Done.
