### ISSUE TITLE
Switch video thumbnail to embed video on click

### ISSUE THREAD

**Issue by ismakutl** [oSoc17/datascouts#137]
[Tutorial](https://webdesign.tutsplus.com/tutorials/how-to-lazy-load-embedded-youtube-videos--cms-26743)

**Comment by Dakad** [comment]
[Simplest Solution - Use JWPlayer ](https://support.jwplayer.com/customer/portal/articles/1406725-youtube-video-embed)

**Comment by Dakad** [comment]
Partially done.
