### ISSUE TITLE
[Error] TypeError: undefined is not an object (evaluating 't.feed.user.profile_image_url_https')

### ISSUE THREAD

**Issue by xavez** [oSoc17/datascouts#151]
Getting a load of errors for Vimeo and YouTube

[Error] TypeError: undefined is not an object (evaluating 't.feed.user.profile_image_url_https')
render — build.js:4:27770
_render — build.js:3:15895
r — build.js:1:27138
get — build.js:3:11040
Yo — build.js:3:10962
wt — build.js:1:27162
init — build.js:3:12523
u — build.js:3:22194
c — build.js:3:21823
_ — build.js:3:23330
w — build.js:3:24468
C — build.js:3:24995
w — build.js:3:24029
C — build.js:3:24995
(anonieme functie) — build.js:3:26175
_update — build.js:3:14787
r — build.js:1:27128
get — build.js:3:11040
run — build.js:3:11764
Ot — build.js:1:28579
(anonieme functie) — build.js:3:7567
t — build.js:3:7018
promiseReactionJob

	S (build.js:1:19628)
	_render (build.js:3:15939)
	r (build.js:1:27138)
	get (build.js:3:11040)
	Yo (build.js:3:10962)
	wt (build.js:1:27162)
	init (build.js:3:12523)
	u (build.js:3:22194)
	c (build.js:3:21823)
	_ (build.js:3:23330)
	w (build.js:3:24468)
	C (build.js:3:24995)
	w (build.js:3:24029)
	C (build.js:3:24995)
	(anonieme functie) (build.js:3:26175)
	_update (build.js:3:14787)
	r (build.js:1:27128)
	get (build.js:3:11040)
	run (build.js:3:11764)
	Ot (build.js:1:28579)
	(anonieme functie) (build.js:3:7567)
	t (build.js:3:7018)
	promiseReactionJob

**Comment by Dakad** [comment]
#158 
The issue is the YoutubeFeed components receive the twitter feed.
![Screenshoot of devtools](https://user-images.githubusercontent.com/3106338/28849898-a6ae726e-7719-11e7-9b80-fa59905dcb8d.png)
