### ISSUE TITLE
Remove GitHub from services list

### ISSUE THREAD

**Issue by xavez** [oSoc17/datascouts#152]
We now see Github when clicking "Add account", but we shouldn't yet.

<img width="435" alt="screen shot 2017-08-01 at 20 47 49" src="https://user-images.githubusercontent.com/1572885/28841484-b4e63b2e-76fa-11e7-9bf9-dc8e572f1516.png">

**Comment by Dakad** [comment]
Every contributor working on this project should clear his localStorage.

**Comment by xavez** [comment]
@Dakad is this also deployed on osoc.weconnectdata.com?

**Comment by Dakad** [comment]
@xavez Yes. Just clear your localStorage.

**Comment by xavez** [comment]
OK cool, just checking 👍.

Works here by the way. <3
