### ISSUE TITLE
CRUD on Entity

### ISSUE THREAD

**Issue by ismakutl** [oSoc17/datascouts#23]
## CRUD on Entity
It's a new feature to allow CRUD on Entity. Entity is a group of handles

## Model

| **Entities** |
| ------------- |
|   Id (PK)   | 
| name (String) **Not Null**    | 
| url (String) **Unique**|
| image (String)|

- Entity 1 -->1,n [Handles](https://github.com/oSoc17/datascouts/issues/57)
- 1 Entity has 1 or Many Handle
- 1 Entity Belongs To Many Handles
##  Actions
- Create 
- Edit (name)
- Delete (Soft ?)
- Read (fetch)

##  Validations
- Name, URL (no empty)
- Check Internet connection
- Limitation on size and extension (.png, .jpg) -> Check for the mimetype and size

**Comment by xavez** [comment]
Closing this, design is done
