### ISSUE TITLE
Validations & errors & flashmessages

### ISSUE THREAD

**Issue by ismakutl** [oSoc17/datascouts#25]
# Validation

- [x] URL's for the entities and handles should be unique

# Errors

- [x] Input search for an entity
- [x] Input Edit a handle_name_
- [x] Input Edit a handle_url_for the handle

# Flashmessages
- [x] Adding an entity
- [x] Adding a handle for an entity
- [x] Successfully logged in
- [x] Delete an entity
- [x] Delete a handle

**Comment by xavez** [comment]
Closing this, design is done.
