### ISSUE TITLE
Technical research on waterfall

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#30]
Delve deep into the waterfall.js plugin code and find out why we have to create a new instance before the waterfall display updates its content. 

A side effect of creating multiple instances is the accumulation of wf-column elements in the DOM.

### Proposed solution

- [x] Find which piece of code adds all wf-box elements to the columns. 
- [x] Edit the plugin so it updates the content through the compose() method. 
- [x] Add cleanup code.

**Comment by mrvdries** [comment]
Issue was solved by moving code from the constructor to the compose() method. Added a cleanup method deleteEmptyColumns() to stop the accumulation of wf-column elements.

This could perhaps use some optimization.

**Comment by coreation** [comment]
Great!! If this is completely done, close the issue ;)

**Comment by xavez** [comment]
Done, closing

**Comment by coreation** [comment]
I love a good Github cleaning on a sunday evening.
