### ISSUE TITLE
Implement empty states

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#33]
When there is no content to be displayed there should be a call to action.
You can find all visual designs at [this link](https://drive.google.com/drive/folders/0B68rv2OTAiu7OVN5cjNwdDJNR0E) 
- [x] HTML & SASS
    - [x] Empty waterfall: "Steps to add an entity"
    - [x] Empty entities: "Add an entity"
    - [x] Empty handles list: "Add a handle to the entity"
_____
- [x] Vue
    - [x] Empty waterfall: "Steps to add an entity"
    - [x] Empty entities: "Add an entity"
    - [x] Empty handles list: "Add a handle to the entity"

**Comment by xavez** [comment]
@ismakutl can you post the proposed designs in this issue as a reference?

**Comment by mietcls** [comment]
@mrvdries is this done? If so, you can close it. Make it a habit please <3
