### ISSUE TITLE
Implement CRUD on social media handles

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#36]
Users should be able to add/edit/delete handles to their entities. A list of handles should be visible when they select an entity.

Implement CRUD for the handles to the frontend:

- [x] Add handle to entity (POST request)
- [x] Delete handle from entity (DELETE request)
- [x] Edit handle from entity (UPDATE request)
- [x] Display appropriate handles in list when an entity is selected (GET request)

**Comment by xavez** [comment]
Closing this, will report bugs for what doesn’t work.
