### ISSUE TITLE
Implement CRUD on entity

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#37]
Users should be able to add/edit/delete entities. A list of entities should be visible when they open the sidebar.

Implement CRUD for the entities to the frontend:

- [x] Add entity (POST request)
- [x] Delete entity (DELETE request)
- [x] Edit entity (UPDATE request)
- [x] Display appropriate entities in list when the sidebar is opened (GET request)

**Comment by xavez** [comment]
Closing this, as it is done. Will log bugs to move forward.
