### ISSUE TITLE
Loading template while fetching data

### ISSUE THREAD

**Issue by ismakutl** [oSoc17/datascouts#38]
There should be some visual indication to the user that the contents of the waterfall display are being loaded. 

### Implementation
- [x] Design loading templates
- [x] Add code to display the templates while content is being loaded
- [x] Dynamically align the templates to the columns of the waterfall display

- [ ] Should be redesigned

**Comment by mrvdries** [comment]
Loading templates align to the columns after the waterfall has been rendered. This results that there is no alignment the first time data is being fetched and the first time after the screen size has been adjusted.

Proposed solutions: 
- Copy code from waterfall plugin to get the necessary variables "early"
- Perhaps more elegantly/optimised: add them to the waterfall display (waterfall.js does not like v-if though!)

**Comment by xavez** [comment]
Good enough for now, closing. Not a priority
