### ISSUE TITLE
CRUD Providers

### ISSUE THREAD

**Issue by Dakad** [oSoc17/datascouts#40]
## Properties
- **ID** (P.K) For Backend 
- FullName
- Mail (unique)
- provider [twitter, facebook, youtube]
- token (Add by upload or fetch in social media)

##  Actions
- Create 
- Edit 
- Delete 
- Read

**Comment by mietcls** [comment]
@Dakad Can you describe this issue a bit better? Anyone should know what this issue is about.

**Comment by mrvdries** [comment]
implemented on backend
