### ISSUE TITLE
Front-end <-> back-end communication

### ISSUE THREAD

**Issue by mrvdries** [oSoc17/datascouts#56]
Describe and detail the communication flow between the front end and backend

## Description
We need to discuss how the front-end and back-end will communicate with each other. This is vital for both ends so they can work at their own pace without having to wait for either one to start working on the same feature. More specifically there needs to be proper communication about how the contents of the waterfall will update to the applied filters, as well as how the CRUDs for entities and handles will work.

## Actions
  - Wich event?
  - What happens?
  - How contact the back-end?
Example : 
 1. On click on 1 entity, must get the handle about this entity so GET /handles/{entity}

**Comment by xavez** [comment]
Closing this, issue is too vague.
