### ISSUE TITLE
Update README.md for the backend

### ISSUE THREAD

**Issue by Dakad** [oSoc17/datascouts#68]
Add a README for the backend. 

## Content

- [x] 1. Navigable Menu
- [x] 2. Description of the backend
- [x] 3. Listings of the technologies
- [ ] 4. Listings of the packages used and their objectives
- [x] 5. Listings of the Routes and Controllers
- [x] 6. Before Started
- [x] 7. Get started
  - [x] - How launch the scheduler/queue/job things
- [ ] 8. Development Hints
- [ ] 9. Further Enhancements
- [ ] 9. Documentation
- [x] 10. License

**Comment by xavez** [comment]
@Dakad this is very well-structured, but maybe we can make the first version of the readme a little bit simpler so you don’t have to spend so much time on it? I’ll leave it up to you how you want to simplify it! :-)

**Comment by Dakad** [comment]
- Clear the frontend & backend
- Amend the READMEs
- Create a release v1.0.0
