### ISSUE TITLE
Fetch Data from more service : Youtube, Github, ...

### ISSUE THREAD

**Issue by Dakad** [oSoc17/datascouts#93]
# Feature #

Add more service into the handle.

- [ ] Github API
- [x] Youtube API
- [ ] VimeoAPI
- [ ] LinkedIn API

**Comment by xavez** [comment]
@Dakad for now we only need one more. Since our time is limited, is it okay to close this issue and make a new one for Vimeo only?

**Comment by Dakad** [comment]
Limited Time. Focus only on Vimeo API on issue #105
