### ISSUE TITLE
Move to digital ocean droplet

### ISSUE THREAD

**Issue by xavez** [oSoc17/datascouts#96]
We need to move to the Digital Ocean droplet before we do anything else.

**Comment by xavez** [comment]
@Dakad please check with @DemianD of the Code9000 team on how to best approach this. He’s a wizard with this kind of stuff.

We need to be able to see the most up to date status of the `develop` branch on that server if possible.

This task has the highest priority right now. If you’re blocked, stalk me so we can fix it ASAP.

**Comment by Dakad** [comment]
[Link to the Code hosted Digital Ocean Droplet](http://osoc.weconnectdata.com)
